/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellChartsRouteImport } from './routes/_shell.charts'
import { Route as ShellHistoryRouteImport } from './routes/_shell.history'
import { Route as ShellLinkRouteImport } from './routes/_shell.link'
import { Route as ShellLoanRouteImport } from './routes/_shell.loan'
import { Route as ShellPeripheralsRouteImport } from './routes/_shell.peripherals'
import { Route as ShellRegisterRouteImport } from './routes/_shell.register'
import { Route as ShellRemoveRouteImport } from './routes/_shell.remove'
import { Route as ShellReportRouteImport } from './routes/_shell.report'
import { Route as ShellReturnRouteImport } from './routes/_shell.return'
import { Route as ShellTermsRouteImport } from './routes/_shell.terms'
import { Route as ShellUnidadesRouteImport } from './routes/_shell.unidades'
import { Route as ShellUsersRouteImport } from './routes/_shell.users'
import { Route as ShellEditIdRouteImport } from './routes/_shell.edit.$id'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChartsRoute = ShellChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHistoryRoute = ShellHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLinkRoute = ShellLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLoanRoute = ShellLoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPeripheralsRoute = ShellPeripheralsRouteImport.update({
  id: '/peripherals',
  path: '/peripherals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRegisterRoute = ShellRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRemoveRoute = ShellRemoveRouteImport.update({
  id: '/remove',
  path: '/remove',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportRoute = ShellReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReturnRoute = ShellReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTermsRoute = ShellTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUnidadesRoute = ShellUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEditIdRoute = ShellEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/charts': typeof ShellChartsRoute
  '/history': typeof ShellHistoryRoute
  '/link': typeof ShellLinkRoute
  '/loan': typeof ShellLoanRoute
  '/peripherals': typeof ShellPeripheralsRoute
  '/register': typeof ShellRegisterRoute
  '/remove': typeof ShellRemoveRoute
  '/report': typeof ShellReportRoute
  '/return': typeof ShellReturnRoute
  '/terms': typeof ShellTermsRoute
  '/unidades': typeof ShellUnidadesRoute
  '/users': typeof ShellUsersRoute
  '/edit/$id': typeof ShellEditIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/charts': typeof ShellChartsRoute
  '/history': typeof ShellHistoryRoute
  '/link': typeof ShellLinkRoute
  '/loan': typeof ShellLoanRoute
  '/peripherals': typeof ShellPeripheralsRoute
  '/register': typeof ShellRegisterRoute
  '/remove': typeof ShellRemoveRoute
  '/report': typeof ShellReportRoute
  '/return': typeof ShellReturnRoute
  '/terms': typeof ShellTermsRoute
  '/unidades': typeof ShellUnidadesRoute
  '/users': typeof ShellUsersRoute
  '/': typeof ShellIndexRoute
  '/edit/$id': typeof ShellEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/charts': typeof ShellChartsRoute
  '/_shell/history': typeof ShellHistoryRoute
  '/_shell/link': typeof ShellLinkRoute
  '/_shell/loan': typeof ShellLoanRoute
  '/_shell/peripherals': typeof ShellPeripheralsRoute
  '/_shell/register': typeof ShellRegisterRoute
  '/_shell/remove': typeof ShellRemoveRoute
  '/_shell/report': typeof ShellReportRoute
  '/_shell/return': typeof ShellReturnRoute
  '/_shell/terms': typeof ShellTermsRoute
  '/_shell/unidades': typeof ShellUnidadesRoute
  '/_shell/users': typeof ShellUsersRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/edit/$id': typeof ShellEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/charts'
    | '/history'
    | '/link'
    | '/loan'
    | '/peripherals'
    | '/register'
    | '/remove'
    | '/report'
    | '/return'
    | '/terms'
    | '/unidades'
    | '/users'
    | '/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/charts'
    | '/history'
    | '/link'
    | '/loan'
    | '/peripherals'
    | '/register'
    | '/remove'
    | '/report'
    | '/return'
    | '/terms'
    | '/unidades'
    | '/users'
    | '/'
    | '/edit/$id'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/charts'
    | '/_shell/history'
    | '/_shell/link'
    | '/_shell/loan'
    | '/_shell/peripherals'
    | '/_shell/register'
    | '/_shell/remove'
    | '/_shell/report'
    | '/_shell/return'
    | '/_shell/terms'
    | '/_shell/unidades'
    | '/_shell/users'
    | '/_shell/'
    | '/_shell/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/charts': {
      id: '/_shell/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ShellChartsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/history': {
      id: '/_shell/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ShellHistoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/link': {
      id: '/_shell/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof ShellLinkRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/loan': {
      id: '/_shell/loan'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof ShellLoanRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/peripherals': {
      id: '/_shell/peripherals'
      path: '/peripherals'
      fullPath: '/peripherals'
      preLoaderRoute: typeof ShellPeripheralsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/register': {
      id: '/_shell/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof ShellRegisterRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/remove': {
      id: '/_shell/remove'
      path: '/remove'
      fullPath: '/remove'
      preLoaderRoute: typeof ShellRemoveRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/report': {
      id: '/_shell/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ShellReportRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/return': {
      id: '/_shell/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ShellReturnRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/terms': {
      id: '/_shell/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof ShellTermsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/unidades': {
      id: '/_shell/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof ShellUnidadesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/edit/$id': {
      id: '/_shell/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof ShellEditIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellChartsRoute: typeof ShellChartsRoute
  ShellHistoryRoute: typeof ShellHistoryRoute
  ShellLinkRoute: typeof ShellLinkRoute
  ShellLoanRoute: typeof ShellLoanRoute
  ShellPeripheralsRoute: typeof ShellPeripheralsRoute
  ShellRegisterRoute: typeof ShellRegisterRoute
  ShellRemoveRoute: typeof ShellRemoveRoute
  ShellReportRoute: typeof ShellReportRoute
  ShellReturnRoute: typeof ShellReturnRoute
  ShellTermsRoute: typeof ShellTermsRoute
  ShellUnidadesRoute: typeof ShellUnidadesRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellEditIdRoute: typeof ShellEditIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellChartsRoute: ShellChartsRoute,
  ShellHistoryRoute: ShellHistoryRoute,
  ShellLinkRoute: ShellLinkRoute,
  ShellLoanRoute: ShellLoanRoute,
  ShellPeripheralsRoute: ShellPeripheralsRoute,
  ShellRegisterRoute: ShellRegisterRoute,
  ShellRemoveRoute: ShellRemoveRoute,
  ShellReportRoute: ShellReportRoute,
  ShellReturnRoute: ShellReturnRoute,
  ShellTermsRoute: ShellTermsRoute,
  ShellUnidadesRoute: ShellUnidadesRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellEditIdRoute: ShellEditIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
